# Generated by Django 5.1 on 2024-10-21 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotify_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wrap_summary", models.JSONField(blank=True, null=True)),
                (
                    "last_generated_wrap_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "wrap_display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_spotify_minutes", models.IntegerField(blank=True, null=True)),
                ("top_artists", models.TextField(blank=True, null=True)),
                ("top_genres", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
